In [5]:
# 필요한 라이브러리를 불러옵니다.
import numpy as np
print('this is sample.')

this is sample.


### 1. 값이 10~49인 numpy array를 만드세요

In [6]:
# array 생성 : np.arange()
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 2. z를 반전하세요.

In [16]:
'''
- np.flipud() : array 위아래 반전
- np.filplr() : array 좌우 반전
- np.flip() : 상하좌우 전체 반전
'''

z = np.flip(z)

print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 3. 반전시킨 z 매트릭스를 10 x 4 매트릭스로 바꾸세요.

In [18]:
# z = 
print(z.reshape(10,4))

[[49 48 47 46]
 [45 44 43 42]
 [41 40 39 38]
 [37 36 35 34]
 [33 32 31 30]
 [29 28 27 26]
 [25 24 23 22]
 [21 20 19 18]
 [17 16 15 14]
 [13 12 11 10]]


### 4. x에서 0이 아닌 요소의 색인을 찾아보세요.

In [19]:
x = np.array([5,6,8,0,1,0,7])
nz_idx = np.where(x != 0)
print(nz_idx)

(array([0, 1, 2, 4, 6], dtype=int64),)


### nan 값 이해하기

In [22]:
print(np.nan == np.nan)
print(np.isnan(np.nan))

import math
print(0.3 == 3 * 0.1)
print(math.isclose(0.1 + 0.2, 0.3))

False
True
False
True


### 5. 12 x 12 매트릭스를 만들어 바둑판 패턴으로 0과 1을 채우세요

In [35]:
x = np.zeros((12, 12))
x[1::2, ::2] = 1 
x[::2, 1::2] = 1
x

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])

### 6. np.tile 을 이용해서 동일한 바둑판 배턴을 만들어보세요

In [54]:
'''
- np.tile(array, 조건) : 배열 복사 
    * 조건1 : reps  ; array 복사 및 바로 옆에 reps 만큼 붙히기
    * 조건2 : (ndim, reps) ; 차원의 개수, reps 만큼 복사 
'''
x = np.array([0,1])

a = np.tile(x,(1,6))
b = np.tile(np.flipud(x),(1,6))
c = np.vstack([a,b])

np.tile(c,(6,1))
# for 


array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

### 7. 1차원 배열이 x에서 값이 5~10인 요소를 0으로 바꾸세요

In [60]:
x = np.array([2,5,3,8,3,34,23,7,10])
print(x)
##################
# 필터링을 사용하세요.
x[(x>=5)&(x<=10)] = 0

##################
print(x)

[ 2  5  3  8  3 34 23  7 10]
[ 2  0  3  0  3 34 23  0  0]


### 8. 0에서 100 사이의 값으로 크기가 10인 1차원 array를 만드세요

In [62]:
''' 
- np.random.uniform(최소,최대, 데이터 수) : 균등 분포 정보 생성
- np.random.normal(최소,최대, 데이터 수) : 정규 분포 정보 생성

'''
x = np.random.uniform(0,100,10)
print(x)

[27.81053807  0.12197429 52.72189375 94.18605552 68.05753792 46.00807867
 14.06319433 45.42062905 60.72826889 13.2584485 ]


### 9. np.allclose() 함수를 사용하여 2개의 array가 같은지를 확인해보세요

In [70]:
'''
- np.allclose(arr1, arr2) : 두 배열이 허용 오차 범위 내에서 요소별로 동일한지 여부를 결정

'''

A = np.array([1e10,1e-8])
B = np.array([1.00001e10,1e-9])

equal = np.allclose(A,B)
print('A와 B는 동일한 array입니다.' if equal is True else '동일하지 않습니다.')

A와 B는 동일한 array입니다.


### 10. 데카르트 좌표를 나타내는 랜덤 8 x 2 행렬을 고려하여 극좌표로 변환해보세요.

In [71]:
coord = np.random.random((10,2))
x, y = coord[:,0], coord[:,1]
r = np.sqrt(np.power(x, 2)+np.power(y, 2))
theta = np.arctan(y/x)
ploar_coord = np.concatenate([r[:,np.newaxis], theta[:,np.newaxis]],axis=1)
print(ploar_coord)

[[1.14288852e+00 1.05789342e+00]
 [7.68341900e-01 1.86663000e-01]
 [2.92695004e-01 8.76805089e-01]
 [8.04081478e-01 1.64570492e-04]
 [1.00914503e+00 8.08750259e-01]
 [6.52687558e-01 1.50668357e+00]
 [9.62272734e-01 4.36014632e-01]
 [8.54009998e-01 7.61592200e-02]
 [4.21583340e-01 4.45818360e-01]
 [9.72263100e-01 1.16060723e+00]]
